import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { format, resolveConfig } from 'prettier';

const here = dirname(fileURLToPath(import.meta.url));
const tableFile = resolve(here, '../src/emoji/source/smiley-table.json');
const assetRoot = resolve(here, '../public/-/emoji');
const outFile = resolve(here, '../src/emoji/generated/emoji-data.ts');

const REGEXP_SPECIALS = /[.*+?^${}()|[\]\\]/g;

function escapeForRegExp(value: string): string {
  return value.replace(REGEXP_SPECIALS, '\\$&');
}

interface Category {
  name: string;
  icon: string;
}

interface SourceEntry {
  name: string;
  category: string;
  symbol: string;
  unicode: string | null;
}

interface SmileyTable {
  categories: Category[];
  excludedCategories: Category[];
  entries: SourceEntry[];
}

interface Entry extends SourceEntry {
  ordinal: number;
  file: string;
  file2x: string | null;
  pattern: string;
  lineBreak: boolean;
}

const table = JSON.parse(readFileSync(tableFile, 'utf8')) as SmileyTable;
const { categories, excludedCategories } = table;

const entries: Entry[] = table.entries.map((entry, ordinal) => {
  const legacy = entry.category === 'LEGACY';
  return {
    ...entry,
    ordinal,
    file: legacy ? `pidgin/${entry.name}.png` : `emoji_one/${entry.unicode}.png`,
    file2x: legacy ? null : `emoji_one/${entry.unicode}_2x.png`,
    pattern: escapeForRegExp(entry.symbol),
    lineBreak: entry.name === 'END',
  };
});

const referenced = new Set<string>();
const missing: string[] = [];
for (const entry of entries) {
  for (const file of [entry.file, entry.file2x]) {
    if (file === null) continue;
    referenced.add(file);
    if (!existsSync(resolve(assetRoot, file))) missing.push(file);
  }
}
for (const category of categories) {
  for (const file of [`category/${category.icon}.png`, `category/${category.icon}_2x.png`]) {
    referenced.add(file);
    if (!existsSync(resolve(assetRoot, file))) missing.push(file);
  }
}

const shipped: string[] = [];
for (const dir of readdirSync(assetRoot, { withFileTypes: true })) {
  if (!dir.isDirectory()) continue;
  for (const file of readdirSync(resolve(assetRoot, dir.name))) {
    shipped.push(`${dir.name}/${file}`);
  }
}
const unreferenced = shipped.filter((f) => !referenced.has(f)).toSorted();

const body = `// generated by web/scripts/gen-emoji.ts — do not edit

export interface EmojiEntry {
  name: string;
  category: EmojiCategoryName;
  symbol: string;
  unicode: string | null;
  ordinal: number;
  file: string;
  file2x: string | null;
  pattern: string;
  lineBreak: boolean;
}

export interface EmojiCategory {
  name: EmojiCategoryName;
  icon: string;
}

export type EmojiCategoryName = ${categories.map((c) => JSON.stringify(c.name)).join(' | ')};

export const EMOJI_CATEGORIES: readonly EmojiCategory[] = ${JSON.stringify(categories, null, 2)};

export const EMOJI: readonly EmojiEntry[] = ${JSON.stringify(entries, null, 2)};
`;

writeFileSync(
  outFile,
  await format(body, { ...(await resolveConfig(outFile)), parser: 'typescript' }),
  'utf8',
);

process.stdout.write(
  [
    `emoji entries        ${entries.length}`,
    `  legacy (pidgin)    ${entries.filter((e) => e.category === 'LEGACY').length}`,
    `  codepoint          ${entries.filter((e) => e.category !== 'LEGACY').length}`,
    `categories kept      ${categories.map((c) => c.name).join(', ')}`,
    `categories excluded  ${excludedCategories.map((c) => c.name).join(', ') || '(none)'}`,
    `referenced files     ${referenced.size}`,
    `shipped files        ${shipped.length}`,
    `missing on disk      ${missing.length ? missing.join(', ') : '(none)'}`,
    `unreferenced shipped ${unreferenced.length ? unreferenced.join(', ') : '(none)'}`,
    '',
  ].join('\n'),
);

if (missing.length) process.exitCode = 1;
